themes:
  - name: "kanagawa"
    colors:
      - "#181616"
      - "#39394D"
      - "#DA6573"
      - "#E17B86"
      - "#FF9E3B"
      - "#8E79B0"
      - "#A189C9"
      - "#78ABC0"
      - "#75B9D5"
      - "#91B468"
      - "#97C062"
      - "#DBB97D"
      - "#E6C07C"
      - "#D3CEB3"
      - "#A09D87"
      - "#C8C093"
  - name: "dragon"
    colors:
      - "#191919"
      - "#DE6E7C"
      - "#E8838F"
      - "#D68C67"
      - "#B279A7"
      - "#B279A7"
      - "#65B8C1"
      - "#61ABDA"
      - "#8BAE68"
      - "#8BAE68"
      - "#D68C67"
      - "#D68C67"
      - "#C9C9C9"
      - "#8E8E8E"
      - "#BBBBBB"
  - name: "zenwritten"
    colors:
      - "#191919"
      - "#303030"
      - "#3D3839"
      - "#404040"
      - "#65435E"
      - "#819B69"
      - "#8BAE68"
      - "#B77E64"
      - "#D68C67"
      - "#6099C0"
      - "#61ABDA"
      - "#B279A7"
      - "#CF86C1"
      - "#66A5AD"
      - "#65B8C1"
      - "#DE6E7C"
      - "#E8838F"
      - "#8E8E8E"
      - "#BBBBBB"
      - "#C9C9C9"
  - name: "zenwritten_monochrome"
    colors:
      - "#191919"
      - "#8E8E8E"
      - "#BBBBBB"
      - "#C9C9C9"
