themes:
  - name: "kanagawa"
    colors:
      - "#1E1E26"
      - "#39394D"
      - "#DA6573"
      - "#E17B86"
      - "#FF9E3B"
      - "#8E79B0"
      - "#A189C9"
      - "#78ABC0"
      - "#75B9D5"
      - "#91B468"
      - "#97C062"
      - "#DBB97D"
      - "#E6C07C"
      - "#D3CEB3"
      - "#A09D87"
      - "#C8C093"
